"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Hammer, Copy, CheckCircle2, FileCode, ListChecks } from "lucide-react";

interface HackersToolkitProps {
  idea: string;
  insights: any;
  scores: any;
}

export function HackersToolkit({ idea, insights, scores }: HackersToolkitProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const beaverInsight = insights?.beaver || insights?.Beaver || "Build with modern tech stack.";
  const cheetahInsight = insights?.cheetah || insights?.Cheetah || "Focus on an MVP first.";

  const readme = `# 🚀 ${idea || "My Startup"}

## Problem
${insights?.fox || insights?.Fox || "Solving a real-world problem for underserved users."}

## Solution
A modern web/mobile application that addresses this gap using cutting-edge technology.

## Tech Stack
- **Frontend:** Next.js / React Native
- **Backend:** Node.js + Express
- **Database:** PostgreSQL (Supabase)
- **AI:** Google Gemini API
- **Payments:** Cashfree / Stripe

## Getting Started
\`\`\`bash
git clone <your-repo-url>
cd my-startup
npm install
npm run dev
\`\`\`

## MVP Milestones
1. Core user authentication
2. Main feature implementation
3. Payment integration
4. Beta launch with 50 users
5. Iterate based on feedback

## Team Needed
Based on Safari Analysis: ${insights?.wolf || insights?.Wolf || "Technical co-founder + Marketing lead"}

---
_Generated by StartupSafari 🐾_
`;

  const tasks = [
    { phase: "Week 1-2", title: "Foundation", tasks: [
      "Set up project repository & CI/CD",
      "Design database schema",
      "Build authentication (Google OAuth + Email)",
      "Create landing page with waitlist"
    ]},
    { phase: "Week 3-4", title: "Core MVP", tasks: [
      "Implement primary user flow",
      "Build core API endpoints",
      "Create responsive UI components",
      "Add basic analytics tracking"
    ]},
    { phase: "Week 5-6", title: "Polish & Launch", tasks: [
      "Integrate payment gateway",
      "User testing with 10 beta users",
      "Fix critical bugs & performance",
      "Launch on Product Hunt / social media"
    ]},
    { phase: "Week 7-8", title: "Growth", tasks: [
      "Analyze user feedback & iterate",
      "Add 2 most-requested features",
      "Set up customer support pipeline",
      "Begin content marketing & SEO"
    ]}
  ];

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="mt-16 p-10 rounded-[3rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl relative overflow-hidden group hover:border-amber-500/20 transition-all duration-700"
    >
      {/* Background Accent */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-amber-500/[0.02] rounded-full blur-[120px] -mr-64 -mt-64 group-hover:bg-amber-500/[0.05] transition-all duration-700" />
      
      <div className="flex items-center gap-6 mb-12">
        <div className="p-4 rounded-[1.25rem] bg-gradient-to-br from-amber-500/20 to-orange-500/10 border border-amber-500/20 text-amber-400 shadow-[0_0_20px_rgba(245,158,11,0.1)] group-hover:scale-110 group-hover:shadow-amber-500/30 transition-all duration-500">
          <Hammer className="w-8 h-8" />
        </div>
        <div>
          <h2 className="text-3xl font-bold font-heading text-white bg-gradient-to-r from-white to-zinc-500 bg-clip-text text-transparent">Beaver's Hacker Toolkit</h2>
          <p className="text-zinc-500 text-sm font-medium">Everything you need to start building your MVP today</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 relative z-10">
        {/* README Generator */}
        <div className="p-8 rounded-3xl bg-white/[0.03] border border-white/10 hover:border-white/20 transition-all duration-500 group/card">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
                <FileCode className="w-5 h-5 text-emerald-400" />
              </div>
              <h3 className="font-bold text-white tracking-wide">README.md</h3>
            </div>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => handleCopy(readme, 'readme')}
              className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-zinc-400 hover:text-white transition-all bg-white/5 hover:bg-white/10 px-4 py-2 rounded-xl border border-white/10 group-hover/card:border-white/30"
            >
              {copied === 'readme' ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied === 'readme' ? 'Copied!' : 'Copy'}
            </motion.button>
          </div>
          <div className="relative">
            <pre className="text-xs text-zinc-400 font-mono bg-[#020205] p-6 rounded-2xl overflow-auto max-h-[32rem] border border-white/5 leading-relaxed whitespace-pre-wrap break-words custom-scrollbar">
              {readme}
            </pre>
            <div className="absolute inset-x-0 bottom-0 h-10 bg-gradient-to-t from-[#020205] to-transparent rounded-b-2xl pointer-events-none" />
          </div>
        </div>

        {/* Task Board */}
        <div className="p-8 rounded-3xl bg-white/[0.03] border border-white/10 hover:border-white/20 transition-all duration-500 group/card">
          <div className="flex items-center gap-3 mb-8">
            <div className="p-2 rounded-lg bg-violet-500/10 border border-violet-500/20">
              <ListChecks className="w-5 h-5 text-violet-400" />
            </div>
            <h3 className="font-bold text-white tracking-wide">Sprint Roadmap</h3>
          </div>
          <div className="space-y-8">
            {tasks.map((phase, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.5 }}
                className="relative"
              >
                <div className="flex items-center gap-4 mb-4">
                  <div className="text-[9px] font-black text-electric-blue uppercase tracking-[0.2em] bg-electric-blue/10 px-3 py-1 rounded-full border border-electric-blue/20 shadow-[0_0_15px_rgba(59,130,246,0.1)]">{phase.phase}</div>
                  <span className="text-sm font-bold text-white group-hover/card:text-electric-blue transition-colors">{phase.title}</span>
                </div>
                <div className="space-y-3.5 pl-6 border-l border-white/5 ml-3">
                  {phase.tasks.map((task, j) => (
                    <motion.div 
                      key={j} 
                      whileHover={{ x: 4 }}
                      className="flex items-center gap-4 group/item cursor-default"
                    >
                      <div className="w-5 h-5 rounded-full border-2 border-white/10 group-hover/item:border-emerald-500 group-hover/item:bg-emerald-500/10 transition-all flex-shrink-0 flex items-center justify-center">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 scale-0 group-hover/item:scale-100 transition-transform duration-300" />
                      </div>
                      <span className="text-xs text-zinc-500 group-hover/item:text-zinc-200 transition-colors font-medium">{task}</span>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

