"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Hammer, Copy, CheckCircle2, FileCode, ListChecks } from "lucide-react";

interface HackersToolkitProps {
  idea: string;
  insights: any;
  scores: any;
}

export function HackersToolkit({ idea, insights, scores }: HackersToolkitProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const beaverInsight = insights?.beaver || insights?.Beaver || "Build with modern tech stack.";
  const cheetahInsight = insights?.cheetah || insights?.Cheetah || "Focus on an MVP first.";

  const readme = `# 🚀 ${idea || "My Startup"}

## Problem
${insights?.fox || insights?.Fox || "Solving a real-world problem for underserved users."}

## Solution
A modern web/mobile application that addresses this gap using cutting-edge technology.

## Tech Stack
- **Frontend:** Next.js / React Native
- **Backend:** Node.js + Express
- **Database:** PostgreSQL (Supabase)
- **AI:** Google Gemini API
- **Payments:** Cashfree / Stripe

## Getting Started
\`\`\`bash
git clone <your-repo-url>
cd my-startup
npm install
npm run dev
\`\`\`

## MVP Milestones
1. Core user authentication
2. Main feature implementation
3. Payment integration
4. Beta launch with 50 users
5. Iterate based on feedback

## Team Needed
Based on Safari Analysis: ${insights?.wolf || insights?.Wolf || "Technical co-founder + Marketing lead"}

---
_Generated by StartupSafari 🐾_
`;

  const tasks = [
    { phase: "Week 1-2", title: "Foundation", tasks: [
      "Set up project repository & CI/CD",
      "Design database schema",
      "Build authentication (Google OAuth + Email)",
      "Create landing page with waitlist"
    ]},
    { phase: "Week 3-4", title: "Core MVP", tasks: [
      "Implement primary user flow",
      "Build core API endpoints",
      "Create responsive UI components",
      "Add basic analytics tracking"
    ]},
    { phase: "Week 5-6", title: "Polish & Launch", tasks: [
      "Integrate payment gateway",
      "User testing with 10 beta users",
      "Fix critical bugs & performance",
      "Launch on Product Hunt / social media"
    ]},
    { phase: "Week 7-8", title: "Growth", tasks: [
      "Analyze user feedback & iterate",
      "Add 2 most-requested features",
      "Set up customer support pipeline",
      "Begin content marketing & SEO"
    ]}
  ];

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="mt-16 p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl">
      <div className="flex items-center gap-4 mb-10">
        <div className="p-3 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400">
          <Hammer className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-3xl font-bold font-heading">Beaver's Hacker Toolkit</h2>
          <p className="text-zinc-500 text-sm">Everything you need to start building your MVP today</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* README Generator */}
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <FileCode className="w-5 h-5 text-emerald-400" />
              <h3 className="font-bold text-white">README.md</h3>
            </div>
            <button
              onClick={() => handleCopy(readme, 'readme')}
              className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-zinc-500 hover:text-white transition-colors bg-white/5 px-3 py-1.5 rounded-lg border border-white/10"
            >
              {copied === 'readme' ? <CheckCircle2 className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
              {copied === 'readme' ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <pre className="text-xs text-zinc-400 font-mono bg-black/30 p-4 rounded-xl overflow-auto max-h-80 border border-white/5 leading-relaxed whitespace-pre-wrap break-words">
            {readme}
          </pre>
        </div>

        {/* Task Board */}
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
          <div className="flex items-center gap-2 mb-6">
            <ListChecks className="w-5 h-5 text-violet-400" />
            <h3 className="font-bold text-white">Sprint Roadmap</h3>
          </div>
          <div className="space-y-6">
            {tasks.map((phase, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <div className="flex items-center gap-3 mb-3">
                  <div className="text-[10px] font-bold text-electric-blue uppercase tracking-widest bg-electric-blue/10 px-2 py-0.5 rounded-full border border-electric-blue/20">{phase.phase}</div>
                  <span className="text-sm font-bold text-white">{phase.title}</span>
                </div>
                <div className="space-y-2 pl-4 border-l border-white/5">
                  {phase.tasks.map((task, j) => (
                    <div key={j} className="flex items-center gap-3 group cursor-default">
                      <div className="w-4 h-4 rounded-full border border-white/20 group-hover:border-emerald-400 group-hover:bg-emerald-400/20 transition-all flex-shrink-0" />
                      <span className="text-xs text-zinc-400 group-hover:text-zinc-200 transition-colors">{task}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
